namespace DotNetGcpApp.Models
{
    /// <summary>
    /// User model representing a user record in PostgreSQL database
    /// This model is used to store user information in Cloud SQL
    /// </summary>
    public class User
    {
        /// <summary>
        /// Unique identifier for the user (auto-generated by database)
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Full name of the user
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Email address of the user (must be unique)
        /// </summary>
        public string Email { get; set; } = string.Empty;

        /// <summary>
        /// Timestamp when the user was created (stored in UTC)
        /// </summary>
        public DateTime CreatedAt { get; set; }
    }
}
